http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    secure-headers:
      headers:
        accessControlAllowMethods:
        - GET
        - OPTIONS
        - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
        - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        stsPreload: true

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
