global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: wp_network

http:
  routers:
    dashboard:
      rule: "Host(`traefik.domain.anda`)"
      service: api@internal
      entryPoints:
      - websecure
      middlewares:
      - secure-headers
      - dashboard-auth

  middlewares:
    secure-headers:
      headers:
        referrerPolicy: "same-origin"
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        stsPreload: true

    dashboard-auth:
      basicAuth:
        users:
        - "user:passwordhash"

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

certificatesResolvers:
  letsencrypt:
    acme:
      email: email@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}
